name: Build check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  all:
    name: Build check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install npm modules
        run: yarn install
      - name: Build
        run: yarn build